Models/BranchOffice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cities_States.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BranchOffice
    {
        public int BranchID { get; set; }
        public int ClientID { get; set; }
        public string BranchCode { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string BranchAddress { get; set; }
        public bool IsCLRALicenseApplicable { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> CLRALicenseExpiry { get; set; }
        public string CLRALicense { get; set; }
    
        public virtual Client Client { get; set; }
    }
}

Controllers/BranchOfficesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Cities_States.Models;

namespace Cities_States.Controllers
{
    public class BranchOfficesController : Controller
    {
        private hrm_dbEntities4 db = new hrm_dbEntities4();

        // GET: BranchOffices
        public ActionResult Index(int? clientId)
        {
            var clients = db.Clients.ToList();
            ViewBag.Clients = new SelectList(clients, "ClientID", "ClientName");

            var branchOffices = db.BranchOffices.Include(b => b.Client);

            if (clientId.HasValue)
            {
                branchOffices = branchOffices.Where(b => b.ClientID == clientId.Value);
            }

            return View(branchOffices.ToList());
        }

        public ActionResult FilterBranchOffices(int clientId)
        {
            var branchOffices = db.BranchOffices.Include(b => b.Client).Where(b => b.ClientID == clientId).ToList();
            return PartialView("_BranchOfficeList", branchOffices);
        }
        public ActionResult DownloadFilteredClientList(int? clientId)
        {
            var branchOffices = db.BranchOffices.Include(b => b.Client);

            if (clientId.HasValue)
            {
                branchOffices = branchOffices.Where(b => b.ClientID == clientId.Value);
            }

            var csv = new StringBuilder();
            csv.AppendLine("BranchID,ClientName,District,BranchAddress,CLRALicenseExpiry");

            foreach (var branch in branchOffices)
            {
                csv.AppendLine($"{branch.BranchID},{branch.Client.ClientName},{branch.District},{branch.BranchAddress},{branch.CLRALicenseExpiry}");
            }

            return File(new System.Text.UTF8Encoding().GetBytes(csv.ToString()), "text/csv", "FilteredClientList.csv");
        }
        public ActionResult DownloadCompleteClientList()
        {
            var clients = db.BranchOffices.ToList();
            var csv = new StringBuilder();
            csv.AppendLine("BranchID,ClientID,BranchCode,State,District,BranchAddress,CLRALicenseExpiry");

            foreach (var client in clients)
            {
                csv.AppendLine($"{client.BranchID},{client.Client.ClientName},{client.BranchCode},{client.State},{client.District},{client.BranchAddress},{client.CLRALicenseExpiry}");
            }

            return File(new System.Text.UTF8Encoding().GetBytes(csv.ToString()), "text/csv", "CompleteClientList.csv");
        }


        // GET: BranchOffices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BranchOffice branchOffice = db.BranchOffices.Find(id);
            if (branchOffice == null)
            {
                return HttpNotFound();
            }
            return View(branchOffice);
        }

        public ActionResult Create()
        {
            ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "ClientName");
            List<state> states = db.states.ToList();
            ViewBag.States = new SelectList(states, "StateID", "StateName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientID,BranchCode,StateID,DistrictID,BranchAddress,IsCLRALicenseApplicable,CLRALicenseExpiry")] BranchOffice branchOffice, int? State, int? District, HttpPostedFileBase CLRALicenseUpload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Check for duplicate branch code for the same client
                    if (db.BranchOffices.Any(b => b.ClientID == branchOffice.ClientID && b.BranchCode == branchOffice.BranchCode))
                    {
                        ModelState.AddModelError("BranchCode", "Branch Code already exists for this client.");
                        ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "ClientName", branchOffice.ClientID);
                        ViewBag.States = new SelectList(db.states, "StateID", "StateName");
                        return View(branchOffice);
                    }

                    if (State.HasValue)
                    {
                        var stateName = db.states.Where(s => s.StateID == State.Value).Select(s => s.StateName).FirstOrDefault();
                        branchOffice.State = stateName;
                    }

                    if (District.HasValue)
                    {
                        var districtName = db.Districts.Where(d => d.DistrictID == District.Value).Select(d => d.DistrictName).FirstOrDefault();
                        branchOffice.District = districtName;
                    }

                    if (branchOffice.IsCLRALicenseApplicable)
                    {
                        if (CLRALicenseUpload != null && CLRALicenseUpload.ContentLength > 0)
                        {
                            try
                            {
                                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(CLRALicenseUpload.FileName);
                                var filePath = Path.Combine(Server.MapPath("~/Images/"), fileName);
                                CLRALicenseUpload.SaveAs(filePath);
                                branchOffice.CLRALicense = "/Images/" + fileName;
                            }
                            catch (Exception ex)
                            {
                                ModelState.AddModelError("", "Error saving image: " + ex.Message);
                                return View(branchOffice);
                            }
                        }
                    }
                    else
                    {
                        branchOffice.CLRALicense = null;
                    }

                    db.BranchOffices.Add(branchOffice);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ClientID = new SelectList(db.Clients, "ClientID", "ClientName", branchOffice.ClientID);
                ViewBag.States = new SelectList(db.states, "StateID", "StateName");
                return View(branchOffice);
            }
            catch
            {
                ViewBag.CreateBranchError = "An error occurred while adding the branch. Please try again later.";
                return View(branchOffice);
            }
           
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BranchOffice branchOffice = db.BranchOffices.Find(id);
            if (branchOffice == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clients = new SelectList(db.Clients, "ClientID", "ClientName", branchOffice.ClientID);
            List<state> states = db.states.ToList();
            ViewBag.States = new SelectList(states, "StateName", "StateName", branchOffice.State);
            List<District> districts = db.Districts.Where(d => d.state.StateName == branchOffice.State).ToList();
            ViewBag.Districts = new SelectList(districts, "DistrictName", "DistrictName", branchOffice.District);

            return View(branchOffice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BranchID,ClientID,BranchCode,State,District,BranchAddress,IsCLRALicenseApplicable,CLRALicenseExpiry")] BranchOffice branchOffice, HttpPostedFileBase CLRALicenseUpload)
        {
            if (ModelState.IsValid)
            {
                var existingBranchOffice = db.BranchOffices.Find(branchOffice.BranchID);
                if (existingBranchOffice == null)
                {
                    return HttpNotFound();
                }

                if (db.BranchOffices.Any(b => b.ClientID == branchOffice.ClientID && b.BranchCode == branchOffice.BranchCode && b.BranchID != branchOffice.BranchID))
                {
                    ModelState.AddModelError("BranchCode", "Branch Code already exists for this client.");
                    ViewBag.Clients = new SelectList(db.Clients, "ClientID", "ClientName", branchOffice.ClientID);
                    ViewBag.States = new SelectList(db.states, "StateName", "StateName", branchOffice.State);
                    ViewBag.Districts = new SelectList(db.Districts.Where(d => d.state.StateName == branchOffice.State), "DistrictName", "DistrictName", branchOffice.District);
                    return View(branchOffice);
                }

                if (CLRALicenseUpload != null && CLRALicenseUpload.ContentLength > 0)
                {
                    try
                    {
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(CLRALicenseUpload.FileName);
                        var filePath = Path.Combine(Server.MapPath("~/Images/"), fileName);
                        CLRALicenseUpload.SaveAs(filePath);
                        branchOffice.CLRALicense = "/Images/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Error saving image: " + ex.Message);
                        return View(branchOffice);
                    }
                }
                else
                {
                    branchOffice.CLRALicense = existingBranchOffice.CLRALicense;
                }

                db.Entry(existingBranchOffice).CurrentValues.SetValues(branchOffice);
                db.SaveChanges();

Views/BranchOffices/Create.cshtml
@model Cities_States.Models.BranchOffice

@{
    ViewBag.Title = "Create";
}
@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.CreateBranchError
    </div>
}
<style>
    .form-group {
        margin-bottom: 20px;
    }

    .card-header {
        background-color: #007bff;
        color: #fff;
    }

    .card-body {
        padding: 30px;
    }

    .btn-back {
        margin-top: 20px;
    }

    .form-check-label {
        cursor: pointer;
    }

    .form-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
    }

    .form-check-input {
        margin-top: 5px;
    }

    .form-check-label {
        margin-left: 5px;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Create Branch Office</h2>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "BranchOffices", FormMethod.Post, new { enctype = "multipart/form-data", @id = "createForm" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            <h4>Branch Office</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <label for="ClientID" class="form-label">Client ID</label>
                                @Html.DropDownList("ClientID", (SelectList)ViewBag.ClientID, "Select Client", htmlAttributes: new { @class = "form-control", @required = "required" })
                                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label for="BranchCode" class="form-label">Branch Code</label>
                                @Html.EditorFor(model => model.BranchCode, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                @Html.ValidationMessageFor(model => model.BranchCode, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="State" class="form-label">State</label>
                                    @Html.DropDownList("State", ViewBag.States as SelectList, "Select State", new { @id = "state", @class = "form-control", @required = "required" })
                                </div>
                                <div class="col-md-6">
                                    <label for="District" class="form-label">District</label>
                                    @Html.DropDownList("District", new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "Select District", new { @id = "district", @class = "form-control", @required = "required" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="BranchAddress" class="form-label">Branch Address</label>
                                @Html.EditorFor(model => model.BranchAddress, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                @Html.ValidationMessageFor(model => model.BranchAddress, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group form-check">
                                <input class="form-check-input" type="checkbox" id="isCLRA" />
                                <label class="form-check-label" for="isCLRA">Is CLRA license applicable for this site?</label>
                                @Html.HiddenFor(model => model.IsCLRALicenseApplicable, new { id = "isCLRAHidden" })
                            </div>

                            <div class="form-group" id="fileUploadGroup" style="display: none;">
                                <label for="CLRALicenseUpload" class="form-label">Upload CLRA License</label>
                                <input type="file" id="CLRALicenseUpload" name="CLRALicenseUpload" class="form-control" />
                            </div>

                            <div class="form-group">
                                <label for="CLRALicenseExpiry" class="form-label">License valid till</label>
                                <input type="date" class="form-control" id="CLRALicenseExpiry" name="CLRALicenseExpiry" required />
                                @Html.ValidationMessageFor(model => model.CLRALicenseExpiry, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary btn-block">Create</button>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="row justify-content-center btn-back">
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            $("#state").change(function () {
                var stateId = $(this).val();
                if (stateId !== "") {
                    $.ajax({
                        url: '@Url.Action("GetDistrictsByState", "BranchOffices")',
                        type: 'GET',
                        data: { stateId: stateId },
                        success: function (result) {
                            var districtDropdown = $("#district");
                            districtDropdown.empty();
                            districtDropdown.append('<option value="">Select District</option>');
                            $.each(result, function (index, district) {
                                districtDropdown.append($('<option></option>').val(district.DistrictID).text(district.DistrictName));
                            });
                        }
                    });
                } else {
                    $("#district").empty().append('<option value="">Select District</option>');
                }
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            function toggleFileUpload() {
                var isChecked = $('#isCLRA').is(':checked');
                $('#fileUploadGroup').toggle(isChecked);
                $('#isCLRAHidden').val(isChecked ? 'true' : 'false');
                if (!isChecked) {
                    $('#CLRALicenseUpload').val('');
                }
            }

            // Initialize on document ready
            toggleFileUpload();

            // Handle checkbox change
            $('#isCLRA').change(function () {
                toggleFileUpload();
            });

            // File validation
            $('#CLRALicenseUpload').change(function () {
                var file = this.files[0];
                var fileSize = file.size;
                var maxSize = 2 * 1024 * 1024;
                var allowedTypes = ['image/jpeg', 'image/png', 'image/jpg'];

                if (allowedTypes.indexOf(file.type) === -1) {
                    alert('Only JPG, JPEG, or PNG files are allowed.');
                    $(this).val('');
                    return false;
                }

                if (fileSize > maxSize) {
                    alert('File size must be less than 2MB.');
                    $(this).val('');
                    return false;
                }
            });

            // Form validation before submission
            $('#createForm').submit(function () {
                var isValid = true;

                if ($('#ClientID').val() === '') {
                    alert('Please select a Client.');
                    isValid = false;
                }
                if ($('#BranchCode').val().trim() === '') {
                    alert('Please enter a Branch Code.');
                    isValid = false;
                }
                if ($('#state').val() === '') {
                    alert('Please select a State.');
                    isValid = false;
                }
                if ($('#district').val() === '') {
                    alert('Please select a District.');
                    isValid = false;
                }
                if ($('#BranchAddress').val().trim() === '') {
                    alert('Please enter a Branch Address.');
                    isValid = false;
                }
                if ($('#isCLRA').is(':checked') && $('#CLRALicenseUpload').val() === '') {
                    alert('Please upload a CLRA License.');
                    isValid = false;
                }
                if ($('#CLRALicenseExpiry').val() === '') {
                    alert('Please enter the License valid till date.');
                    isValid = false;
                }

                return isValid;
            });
        });
    </script>
}

Views/BranchOffices/Edit.cshtml
@model Cities_States.Models.BranchOffice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "BranchOffices", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Edit Branch Office</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.BranchID)

                        <div class="form-group">
                            <label for="ClientID" class="form-label">Client ID</label>
                            <!-- Use ViewBag.Clients to populate the dropdown -->
                            @Html.DropDownList("ClientID", ViewBag.Clients as SelectList, "Select Client", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            <label for="BranchCode" class="form-label">Branch Code</label>
                            @Html.EditorFor(model => model.BranchCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BranchCode, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="State" class="control-label col-md-2">State</label>
                            <div class="col-md-10">
                                @Html.DropDownList("State", ViewBag.States as SelectList, "Select State", new { @id = "state", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="District" class="control-label col-md-2">District</label>
                            <div class="col-md-10">
                                @Html.DropDownList("District", ViewBag.Districts as SelectList, "Select District", new { @id = "district", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="BranchAddress" class="form-label">Branch Address</label>
                            @Html.EditorFor(model => model.BranchAddress, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BranchAddress, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group form-check">
                            <input class="form-check-input" type="checkbox" id="isCLRA" @if (Model.IsCLRALicenseApplicable) { <text> checked="checked" </text> } />
                            <label class="form-check-label" for="isCLRA">Is CLRA license applicable for this site?</label>
                            @Html.HiddenFor(model => model.IsCLRALicenseApplicable) <!-- Add a hidden field to store the value -->
                        </div>

                        <!-- File Upload for CLRA License -->
                        <div class="form-group" id="fileUploadGroup" @if (!Model.IsCLRALicenseApplicable) { <text> style="display: none;" </text> }>
                            <label for="CLRALicenseUpload" class="form-label">Upload CLRA License</label>
                            <input type="file" id="CLRALicenseUpload" name="CLRALicenseUpload" class="form-control" />
                            <!-- Image preview -->
                            @if (!string.IsNullOrEmpty(Model.CLRALicense))
                            {
                                <img src="@Url.Content(Model.CLRALicense)" alt="Uploaded License" class="img-thumbnail" style="max-width: 200px; margin-top: 10px;" />
                            }
                        </div>



                        <div class="form-group">
                            <label for="CLRALicenseExpiry" class="form-label">License valid till</label>
                            @Html.EditorFor(model => model.CLRALicenseExpiry, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CLRALicenseExpiry, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="row justify-content-center mt-3">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#state').change(function () {
                var stateName = $(this).val();
                $.getJSON('@Url.Action("GetDistrictsByState", "BranchOffices")', { stateName: stateName }, function (data) {
                    var items = '<option>Select District</option>';
                    $.each(data, function (i, district) {
                        items += "<option value='" + district.DistrictName + "'>" + district.DistrictName + "</option>";
                    });
                    $('#district').html(items);
                });
            });
            
        });
    </script>
    <script>
        $(document).ready(function () {
            // Initialize the file upload visibility based on checkbox
            function toggleFileUpload() {
                var isChecked = $('#isCLRA').is(':checked');
                $('#fileUploadGroup').toggle(isChecked);
                $('#isCLRAHidden').val(isChecked ? 'true' : 'false');
                if (!isChecked) {
                    $('#CLRALicenseUpload').val('');
                }
            }

            // Handle checkbox change
            $('#isCLRA').change(function () {
                toggleFileUpload();
            });

            // Initialize on document ready
            toggleFileUpload();

            // File validation
            $('#CLRALicenseUpload').change(function () {
                var file = this.files[0];
                var fileSize = file.size; // in bytes
                var maxSize = 2 * 1024 * 1024; // 2MB
                var allowedTypes = ['image/jpeg', 'image/png', 'image/jpg'];

                if (allowedTypes.indexOf(file.type) === -1) {
                    alert('Only JPG, JPEG, or PNG files are allowed.');
                    $(this).val(''); // Clear the file input
                    return false;
                }

                if (fileSize > maxSize) {
                    alert('File size must be less than 2MB.');
                    $(this).val(''); // Clear the file input
                    return false;
                }
            });
        });
    </script>
}

Views/BranchOffices/Index.cshtml
@model IEnumerable<Cities_States.Models.BranchOffice>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container-fluid">
    <div class="row mb-3">
        <div class="col">
            <p>
                <a href="@Url.Action("DownloadCompleteClientList", "BranchOffices")" class="btn btn-success mr-2">Download Complete Client List</a>
                <button id="downloadFilteredClientList" class="btn btn-success">Download Filtered Client List</button>
            </p>
        </div>
        <div class="col">
            <div class="d-flex justify-content-end align-items-center">
                <div class="flex-grow-1 mr-2">
                    @Html.DropDownList("ClientID", ViewBag.Clients as SelectList, "Select Client", new { @class = "form-control", id = "clientDropdown" })
                </div>
                <div>
                    <a href="@Url.Action("Create")" class="btn btn-primary btn-block">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                            <path d="M7 1.5a.5.5 0 0 1 .5.5V7h5.5a.5.5 0 0 1 0 1H7v5.5a.5.5 0 0 1-1 0V8H.5a.5.5 0 0 1 0-1H6V2a.5.5 0 0 1 .5-.5z" />
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<table id="branchTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Client Name</th>
            <th>Client ID</th>
            <th>District</th>
            @*<th>Branch Address</th>*@
            <th>Branch Code</th>
            <th>CLRA License Expiry</th>
            <th>CLRA License Applicable</th>
            <th>CLRA License Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="branchOfficeList">
        @Html.Partial("_BranchOfficeList", Model)
    </tbody>
</table>

@section scripts {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#branchTable').DataTable();

            $('#clientDropdown').change(function () {
                var clientId = $(this).val();
                var url = '@Url.Action("Index", "BranchOffices")' + '?clientId=' + clientId;
                window.location.href = url;
            });

            $('#downloadFilteredClientList').click(function () {
                var clientId = $('#clientDropdown').val();
                if (clientId) {
                    var url = '@Url.Action("DownloadFilteredClientList", "BranchOffices")' + '?clientId=' + clientId;
                    window.location.href = url;
                } else {
                    alert("Please select a client to download the filtered list.");
                }
            });
        });
    </script>
}